In [195]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [196]:
test_csv = pd.read_csv('Test.csv')
train_csv= pd.read_csv('Train.csv')
subm_csv = pd.read_csv('Submission.csv')

In [197]:
train_csv.head(3)

EmpID  EmpName LanguageOfCommunication  Age  Gender  \
0  11041     John                 English   35    Male   
1  15079  William                 English   26    Male   
2  18638    James                 English   36  Female   

  JobProfileIDApplyingFor HighestDegree             DegreeBranch  \
0                 JR85289        B.Tech               Electrical   
1                 JR87525        B.Tech  Artificial Intelligence   
2                 JR87525           PhD         Computer Science   

  GraduatingInstitute  LatestDegreeCGPA  ...  CurrentCTC  ExpectedCTC  \
0              Tier 1                 7  ...          21           26   
1              Tier 3                 7  ...          15           19   
2              Tier 1                 6  ...          15           24   

   MartialStatus  EmpScore CurrentDesignation  CurrentCompanyType  \
0        Married         5                SSE          Enterprise   
1        Married         5                 BA            MidSized   
2         Single         5                SDE            MidSized   

  DepartmentInCompany TotalLeavesTaken BiasInfluentialFactor  FitmentPercent  
0              Design               20      YearsOfExperince           95.40  
1         Engineering                6                   NaN           67.09  
2         Engineering               19                Gender           91.26  

[3 rows x 22 columns]

In [198]:
train_csv.isnull().sum()

EmpID                         0
EmpName                       0
LanguageOfCommunication       0
Age                           0
Gender                        0
JobProfileIDApplyingFor       0
HighestDegree                 0
DegreeBranch                  0
GraduatingInstitute           0
LatestDegreeCGPA              0
YearsOfExperince              0
GraduationYear                0
CurrentCTC                    0
ExpectedCTC                   0
MartialStatus                 0
EmpScore                      0
CurrentDesignation            0
CurrentCompanyType            0
DepartmentInCompany           0
TotalLeavesTaken              0
BiasInfluentialFactor      3336
FitmentPercent                0
dtype: int64

In [199]:
train_csv.BiasInfluentialFactor.value_counts()

DegreeBranch          2858
Gender                2605
YearsOfExperince      1561
CurrentCompanyType    1174
EmpScore               659
HighestDegree          582
Ethinicity             328
MartialStatus          280
LatestDegreeCGPA       262
Name: BiasInfluentialFactor, dtype: int64

In [200]:
train_csv['BiasInfluentialFactor'] = train_csv['BiasInfluentialFactor'].fillna(0)

In [201]:
train_csv = train_csv.replace(to_replace =0,value = "Never")

In [202]:
train_csv.head(3)

EmpID  EmpName LanguageOfCommunication  Age  Gender  \
0  11041     John                 English   35    Male   
1  15079  William                 English   26    Male   
2  18638    James                 English   36  Female   

  JobProfileIDApplyingFor HighestDegree             DegreeBranch  \
0                 JR85289        B.Tech               Electrical   
1                 JR87525        B.Tech  Artificial Intelligence   
2                 JR87525           PhD         Computer Science   

  GraduatingInstitute  LatestDegreeCGPA  ...  CurrentCTC  ExpectedCTC  \
0              Tier 1                 7  ...          21           26   
1              Tier 3                 7  ...          15           19   
2              Tier 1                 6  ...          15           24   

   MartialStatus  EmpScore CurrentDesignation  CurrentCompanyType  \
0        Married         5                SSE          Enterprise   
1        Married         5                 BA            MidSized   
2         Single         5                SDE            MidSized   

  DepartmentInCompany TotalLeavesTaken BiasInfluentialFactor  FitmentPercent  
0              Design               20      YearsOfExperince           95.40  
1         Engineering                6                 Never           67.09  
2         Engineering               19                Gender           91.26  

[3 rows x 22 columns]

In [203]:
list_of = train_csv['BiasInfluentialFactor'].value_counts()

In [204]:
from sklearn.preprocessing import LabelEncoder

In [205]:
le = LabelEncoder()
train_new = train_csv

In [206]:
train_new['BiasInfluentialFactor'] = le.fit_transform(train_new.BiasInfluentialFactor)
train_new['LanguageOfCommunication'] = le.fit_transform(train_new.LanguageOfCommunication)
train_new['Gender'] = le.fit_transform(train_new.Gender)
train_new['HighestDegree'] = le.fit_transform(train_new.HighestDegree)
train_new['GraduatingInstitute'] = le.fit_transform(train_new.GraduatingInstitute)
train_new['CurrentDesignation'] = le.fit_transform(train_new.CurrentDesignation)
train_new['MartialStatus'] = le.fit_transform(train_new.MartialStatus)
train_new['CurrentCompanyType'] = le.fit_transform(train_new.CurrentCompanyType)
train_new['DepartmentInCompany'] = le.fit_transform(train_new.DepartmentInCompany)
train_new['JobProfileIDApplyingFor'] = le.fit_transform(train_new.JobProfileIDApplyingFor)
train_new['DegreeBranch'] = le.fit_transform(train_new.DegreeBranch)
train_new['GraduationYear'] = le.fit_transform(train_new.GraduationYear)

In [207]:
train_new.head(4)

EmpID  EmpName  LanguageOfCommunication  Age  Gender  \
0  11041     John                        0   35       1   
1  15079  William                        0   26       1   
2  18638    James                        0   36       0   
3   3941  Charles                        0   29       0   

   JobProfileIDApplyingFor  HighestDegree  DegreeBranch  GraduatingInstitute  \
0                        3              0             2                    0   
1                        4              0             0                    2   
2                        4              7             1                    0   
3                        4              1             5                    1   

   LatestDegreeCGPA  ...  CurrentCTC  ExpectedCTC  MartialStatus  EmpScore  \
0                 7  ...          21           26              0         5   
1                 7  ...          15           19              0         5   
2                 6  ...          15           24              1         5   
3                 5  ...          16           24              0         5   

   CurrentDesignation  CurrentCompanyType  DepartmentInCompany  \
0                   7                   0                    1   
1                   0                   1                    2   
2                   5                   1                    2   
3                   5                   2                    4   

   TotalLeavesTaken  BiasInfluentialFactor  FitmentPercent  
0                20                      9           95.40  
1                 6                      8           67.09  
2                19                      4           91.26  
3                16                      4           72.29  

[4 rows x 22 columns]

In [208]:
feature_cols = train_new.columns

In [209]:
feature_cols

Index(['EmpID', 'EmpName', 'LanguageOfCommunication', 'Age', 'Gender',
       'JobProfileIDApplyingFor', 'HighestDegree', 'DegreeBranch',
       'GraduatingInstitute', 'LatestDegreeCGPA', 'YearsOfExperince',
       'GraduationYear', 'CurrentCTC', 'ExpectedCTC', 'MartialStatus',
       'EmpScore', 'CurrentDesignation', 'CurrentCompanyType',
       'DepartmentInCompany', 'TotalLeavesTaken', 'BiasInfluentialFactor',
       'FitmentPercent'],
      dtype='object')

In [210]:
train_csv.head(4)

EmpID  EmpName  LanguageOfCommunication  Age  Gender  \
0  11041     John                        0   35       1   
1  15079  William                        0   26       1   
2  18638    James                        0   36       0   
3   3941  Charles                        0   29       0   

   JobProfileIDApplyingFor  HighestDegree  DegreeBranch  GraduatingInstitute  \
0                        3              0             2                    0   
1                        4              0             0                    2   
2                        4              7             1                    0   
3                        4              1             5                    1   

   LatestDegreeCGPA  ...  CurrentCTC  ExpectedCTC  MartialStatus  EmpScore  \
0                 7  ...          21           26              0         5   
1                 7  ...          15           19              0         5   
2                 6  ...          15           24              1         5   
3                 5  ...          16           24              0         5   

   CurrentDesignation  CurrentCompanyType  DepartmentInCompany  \
0                   7                   0                    1   
1                   0                   1                    2   
2                   5                   1                    2   
3                   5                   2                    4   

   TotalLeavesTaken  BiasInfluentialFactor  FitmentPercent  
0                20                      9           95.40  
1                 6                      8           67.09  
2                19                      4           91.26  
3                16                      4           72.29  

[4 rows x 22 columns]

In [211]:
import xgboost
import csv as csv
from xgboost import plot_importance
from matplotlib import pyplot
from sklearn.model_selection import cross_val_score,KFold
from sklearn.model_selection import  train_test_split
from sklearn.metrics import mean_absolute_error
import matplotlib.pyplot as plt
from sklearn.model_selection import learning_curve, GridSearchCV
from scipy.stats import skew
from collections import OrderedDict

In [241]:
test_dataset = test_csv

In [242]:
test_dataset.head(4)

EmpID  EmpName LanguageOfCommunication  Age Gender JobProfileIDApplyingFor  \
0   5664     Theo                  Native   35   Male                 JR85289   
1  23568   Vernie                 English   35   Male                 JR85289   
2  21490  Wendell                 English   28   Male                 JR87525   
3   8363     West                   Hindi   37   Male                 JR87525   

  HighestDegree             DegreeBranch GraduatingInstitute  \
0           PhD   Information Technology              Tier 2   
1        B.Tech   Information Technology              Tier 3   
2        M.Tech  Artificial Intelligence              Tier 2   
3            MS         Computer Science              Tier 2   

   LatestDegreeCGPA  YearsOfExperince  GraduationYear  CurrentCTC  \
0                 5                 5            2016          27   
1                 9                12            2009          29   
2                 9                 2            2019          18   
3                 8                11            2010           7   

   ExpectedCTC MartialStatus  EmpScore CurrentDesignation CurrentCompanyType  \
0           34        Single         4                SDE         Enterprise   
1           33       Married         4                 EM         Enterprise   
2           25       Married         3                SDE            Startup   
3           12        Single         5                 DS         Enterprise   

  DepartmentInCompany  TotalLeavesTaken  
0             Finance                18  
1         Engineering                 8  
2         Engineering                18  
3             Product                17

In [243]:
test_final = pd.DataFrame()

In [244]:
test_final['EmpID'] =  test_dataset['EmpID']
test_final['EmpName']= test_dataset['EmpName']

In [245]:
test_final = test_dataset.drop(['EmpID','EmpName'], axis=1)

In [246]:
test_final.head(4)

LanguageOfCommunication  Age Gender JobProfileIDApplyingFor HighestDegree  \
0                  Native   35   Male                 JR85289           PhD   
1                 English   35   Male                 JR85289        B.Tech   
2                 English   28   Male                 JR87525        M.Tech   
3                   Hindi   37   Male                 JR87525            MS   

              DegreeBranch GraduatingInstitute  LatestDegreeCGPA  \
0   Information Technology              Tier 2                 5   
1   Information Technology              Tier 3                 9   
2  Artificial Intelligence              Tier 2                 9   
3         Computer Science              Tier 2                 8   

   YearsOfExperince  GraduationYear  CurrentCTC  ExpectedCTC MartialStatus  \
0                 5            2016          27           34        Single   
1                12            2009          29           33       Married   
2                 2            2019          18           25       Married   
3                11            2010           7           12        Single   

   EmpScore CurrentDesignation CurrentCompanyType DepartmentInCompany  \
0         4                SDE         Enterprise             Finance   
1         4                 EM         Enterprise         Engineering   
2         3                SDE            Startup         Engineering   
3         5                 DS         Enterprise             Product   

   TotalLeavesTaken  
0                18  
1                 8  
2                18  
3                17

In [247]:
test_final['LanguageOfCommunication'] = le.fit_transform(test_final.LanguageOfCommunication)
test_final['Gender'] = le.fit_transform(test_final.Gender)
test_final['HighestDegree'] = le.fit_transform(test_final.HighestDegree)
test_final['GraduatingInstitute'] = le.fit_transform(test_final.GraduatingInstitute)
test_final['CurrentDesignation'] = le.fit_transform(test_final.CurrentDesignation)
test_final['MartialStatus'] = le.fit_transform(test_final.MartialStatus)
test_final['CurrentCompanyType'] = le.fit_transform(test_final.CurrentCompanyType)
test_final['DepartmentInCompany'] = le.fit_transform(test_final.DepartmentInCompany)
test_final['JobProfileIDApplyingFor'] = le.fit_transform(test_final.JobProfileIDApplyingFor)
test_final['DegreeBranch'] = le.fit_transform(test_final.DegreeBranch)
test_final['GraduationYear'] = le.fit_transform(test_final.GraduationYear)

In [248]:
test_final.head(4)

LanguageOfCommunication  Age  Gender  JobProfileIDApplyingFor  \
0                        2   35       1                        3   
1                        0   35       1                        3   
2                        0   28       1                        4   
3                        1   37       1                        4   

   HighestDegree  DegreeBranch  GraduatingInstitute  LatestDegreeCGPA  \
0              7             5                    1                 5   
1              0             5                    2                 9   
2              4             0                    1                 9   
3              6             1                    1                 8   

   YearsOfExperince  GraduationYear  CurrentCTC  ExpectedCTC  MartialStatus  \
0                 5               7          27           34              1   
1                12               0          29           33              0   
2                 2              10          18           25              0   
3                11               1           7           12              1   

   EmpScore  CurrentDesignation  CurrentCompanyType  DepartmentInCompany  \
0         4                   5                   0                    3   
1         4                   4                   0                    2   
2         3                   5                   2                    2   
3         5                   3                   0                    4   

   TotalLeavesTaken  
0                18  
1                 8  
2                18  
3                17

In [249]:
test_final.columns

Index(['LanguageOfCommunication', 'Age', 'Gender', 'JobProfileIDApplyingFor',
       'HighestDegree', 'DegreeBranch', 'GraduatingInstitute',
       'LatestDegreeCGPA', 'YearsOfExperince', 'GraduationYear', 'CurrentCTC',
       'ExpectedCTC', 'MartialStatus', 'EmpScore', 'CurrentDesignation',
       'CurrentCompanyType', 'DepartmentInCompany', 'TotalLeavesTaken'],
      dtype='object')

In [250]:
train_new.columns

Index(['LanguageOfCommunication', 'Age', 'Gender', 'JobProfileIDApplyingFor',
       'HighestDegree', 'DegreeBranch', 'GraduatingInstitute',
       'LatestDegreeCGPA', 'YearsOfExperince', 'GraduationYear', 'CurrentCTC',
       'ExpectedCTC', 'MartialStatus', 'EmpScore', 'CurrentDesignation',
       'CurrentCompanyType', 'DepartmentInCompany', 'TotalLeavesTaken',
       'BiasInfluentialFactor', 'FitmentPercent'],
      dtype='object')

In [251]:
name_id = pd.DataFrame()

In [252]:
name_id['EmpID'] =  train_new['EmpID']
name_id['EmpName']= train_new['EmpName']

KeyError: 'EmpID'

In [253]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [225]:
train_new.drop(['EmpID','EmpName'], inplace=True,axis = 1)

In [226]:
np.random.seed(0)
df_train, df_test = train_test_split(train_new, train_size = 0.7, test_size = 0.3, random_state = 100)

In [254]:
df_train.head(4)

LanguageOfCommunication  Age  Gender  JobProfileIDApplyingFor  \
301                          0   25       1                        1   
12496                        0   31       0                        3   
2424                         0   30       1                        3   
7487                         0   33       1                        6   

       HighestDegree  DegreeBranch  GraduatingInstitute  LatestDegreeCGPA  \
301                0             0                    2                 7   
12496              7             0                    2                 9   
2424               2             4                    2                 5   
7487               0             1                    1                 7   

       YearsOfExperince  GraduationYear  CurrentCTC  ExpectedCTC  \
301                   2              10          14           20   
12496                 1              11          15           20   
2424                  7               5          27           32   
7487                 10               2          14           24   

       MartialStatus  EmpScore  CurrentDesignation  CurrentCompanyType  \
301                0         1                   4                   2   
12496              0         5                   6                   0   
2424               1         1                   3                   2   
7487               1         3                   7                   1   

       DepartmentInCompany  TotalLeavesTaken  BiasInfluentialFactor  
301                      0                18                      3  
12496                    2                 5                      4  
2424                     1                15                      8  
7487                     2                 4                      9

In [255]:
a = test_final.columns

In [256]:
from sklearn.metrics import classification_report

In [257]:
from sklearn.metrics import accuracy_score
import sklearn as sk
from sklearn import svm
import pandas as pd
import os

In [258]:
df_train.columns

Index(['LanguageOfCommunication', 'Age', 'Gender', 'JobProfileIDApplyingFor',
       'HighestDegree', 'DegreeBranch', 'GraduatingInstitute',
       'LatestDegreeCGPA', 'YearsOfExperince', 'GraduationYear', 'CurrentCTC',
       'ExpectedCTC', 'MartialStatus', 'EmpScore', 'CurrentDesignation',
       'CurrentCompanyType', 'DepartmentInCompany', 'TotalLeavesTaken',
       'BiasInfluentialFactor'],
      dtype='object')

In [259]:
for_fitment = train_new

In [260]:
df_train.head(4)

LanguageOfCommunication  Age  Gender  JobProfileIDApplyingFor  \
301                          0   25       1                        1   
12496                        0   31       0                        3   
2424                         0   30       1                        3   
7487                         0   33       1                        6   

       HighestDegree  DegreeBranch  GraduatingInstitute  LatestDegreeCGPA  \
301                0             0                    2                 7   
12496              7             0                    2                 9   
2424               2             4                    2                 5   
7487               0             1                    1                 7   

       YearsOfExperince  GraduationYear  CurrentCTC  ExpectedCTC  \
301                   2              10          14           20   
12496                 1              11          15           20   
2424                  7               5          27           32   
7487                 10               2          14           24   

       MartialStatus  EmpScore  CurrentDesignation  CurrentCompanyType  \
301                0         1                   4                   2   
12496              0         5                   6                   0   
2424               1         1                   3                   2   
7487               1         3                   7                   1   

       DepartmentInCompany  TotalLeavesTaken  BiasInfluentialFactor  
301                      0                18                      3  
12496                    2                 5                      4  
2424                     1                15                      8  
7487                     2                 4                      9

In [261]:
f = df_train
f.drop(['FitmentPercent'],axis=1,inplace=True)

KeyError: "['FitmentPercent'] not found in axis"

In [234]:
y_train = f.iloc[:,18]
x_train = f.iloc[:,:18]

In [235]:
for_fitment.columns

Index(['LanguageOfCommunication', 'Age', 'Gender', 'JobProfileIDApplyingFor',
       'HighestDegree', 'DegreeBranch', 'GraduatingInstitute',
       'LatestDegreeCGPA', 'YearsOfExperince', 'GraduationYear', 'CurrentCTC',
       'ExpectedCTC', 'MartialStatus', 'EmpScore', 'CurrentDesignation',
       'CurrentCompanyType', 'DepartmentInCompany', 'TotalLeavesTaken',
       'BiasInfluentialFactor'],
      dtype='object')

In [269]:
x_new_train = for_fitment.iloc[:,:18]
y_new_train = for_fitment.iloc[:,19]

In [270]:
x_new_train.head(4)

LanguageOfCommunication  Age  Gender  JobProfileIDApplyingFor  \
0                        0   35       1                        3   
1                        0   26       1                        4   
2                        0   36       0                        4   
3                        0   29       0                        4   

   HighestDegree  DegreeBranch  GraduatingInstitute  LatestDegreeCGPA  \
0              0             2                    0                 7   
1              0             0                    2                 7   
2              7             1                    0                 6   
3              1             5                    1                 5   

   YearsOfExperince  GraduationYear  CurrentCTC  ExpectedCTC  MartialStatus  \
0                12               0          21           26              0   
1                 3               9          15           19              0   
2                 6               6          15           24              1   
3                 6               6          16           24              0   

   EmpScore  CurrentDesignation  CurrentCompanyType  DepartmentInCompany  \
0         5                   7                   0                    1   
1         5                   0                   1                    2   
2         5                   5                   1                    2   
3         5                   5                   2                    4   

   TotalLeavesTaken  
0                20  
1                 6  
2                19  
3                16

In [273]:
ax_test = np.asarray(x_new_train)
ay_test = np.asarray(y_new_train)

In [275]:
ax_test

array([[ 0, 35,  1, ...,  0,  1, 20],
       [ 0, 26,  1, ...,  1,  2,  6],
       [ 0, 36,  0, ...,  1,  2, 19],
       ...,
       [ 1, 37,  1, ...,  0,  1, 20],
       [ 1, 24,  1, ...,  1,  2,  7],
       [ 0, 35,  1, ...,  2,  2, 16]])

In [276]:
ay_test

array([95.4 , 67.09, 91.26, ..., 61.46, 93.64, 93.52])

In [277]:
from sklearn import linear_model

In [278]:
regr = linear_model.LinearRegression()
regr.fit(ax_test, ay_test)

LinearRegression()

In [281]:
predicted= regr.predict(v)

In [282]:
predicted

array([69.95626491, 71.28237066, 78.4837383 , ..., 77.28093018,
       64.75106938, 73.54876424])

In [283]:
test_final['FitmentPercent'] = predicted

In [274]:
model_new = svm.SVC(kernel='linear', gamma='auto',C=20)
model.fit(ax_test, ay_test)

ValueError: Unknown label type: 'continuous'

In [ ]:
pred = model.predict(x_test)

In [113]:
x_train.head(4)

LanguageOfCommunication  Age  Gender  JobProfileIDApplyingFor  \
301                          0   25       1                        1   
12496                        0   31       0                        3   
2424                         0   30       1                        3   
7487                         0   33       1                        6   

       HighestDegree  DegreeBranch  GraduatingInstitute  LatestDegreeCGPA  \
301                0             0                    2                 7   
12496              7             0                    2                 9   
2424               2             4                    2                 5   
7487               0             1                    1                 7   

       YearsOfExperince  GraduationYear  CurrentCTC  ExpectedCTC  \
301                   2              10          14           20   
12496                 1              11          15           20   
2424                  7               5          27           32   
7487                 10               2          14           24   

       MartialStatus  EmpScore  CurrentDesignation  CurrentCompanyType  \
301                0         1                   4                   2   
12496              0         5                   6                   0   
2424               1         1                   3                   2   
7487               1         3                   7                   1   

       DepartmentInCompany  TotalLeavesTaken  
301                      0                18  
12496                    2                 5  
2424                     1                15  
7487                     2                 4

In [114]:
g = df_test

In [165]:
g.head(3)

LanguageOfCommunication  Age  Gender  JobProfileIDApplyingFor  \
9706                         1   32       1                        4   
13001                        1   30       1                        3   
10164                        0   33       0                        3   

       HighestDegree  DegreeBranch  GraduatingInstitute  LatestDegreeCGPA  \
9706               0             4                    0                 8   
13001              0             1                    0                 7   
10164              1             1                    2                 8   

       YearsOfExperince  GraduationYear  CurrentCTC  ExpectedCTC  \
9706                  9               3          11           16   
13001                 7               5           7           17   
10164                10               2          28           35   

       MartialStatus  EmpScore  CurrentDesignation  CurrentCompanyType  \
9706               0         1                   7                   2   
13001              1         4                   3                   2   
10164              1         4                   5                   0   

       DepartmentInCompany  TotalLeavesTaken  BiasInfluentialFactor  \
9706                     1                17                      8   
13001                    2                 4                      1   
10164                    0                11                      4   

       FitmentPercent  
9706            85.15  
13001           73.14  
10164           83.71

In [116]:
g = df_test
y_test = g.iloc[:,18]
x_test = g.iloc[:,:18]

In [117]:
y_train

301      3
12496    4
2424     8
7487     9
7256     7
        ..
79       8
12119    8
8039     9
6936     4
5640     8
Name: BiasInfluentialFactor, Length: 9551, dtype: int64

In [118]:
X = np.asarray(x_train)
Y = np.asarray(y_train)

In [119]:
Y

array([3, 4, 8, ..., 9, 4, 8])

In [120]:
x_test = np.asarray(x_test)
y_test = np.asarray(y_test)

In [121]:
model = svm.SVC(kernel='poly', degree=20)
model.fit(X, Y)
predictions_for_poly = model.predict(x_test)

In [122]:
print(classification_report(y_test,predictions_for_poly))

              precision    recall  f1-score   support

           0       0.36      0.37      0.37       355
           1       0.52      0.47      0.49       884
           2       0.30      0.19      0.23       203
           3       0.07      0.06      0.07        93
           4       0.74      0.84      0.79       756
           5       0.58      0.56      0.57       180
           6       0.18      0.10      0.13        88
           7       0.24      0.12      0.16        75
           8       0.42      0.50      0.46       986
           9       0.77      0.65      0.71       474

    accuracy                           0.53      4094
   macro avg       0.42      0.39      0.40      4094
weighted avg       0.52      0.53      0.52      4094



In [125]:
print(predictions_for_poly)

[8 8 0 ... 8 9 1]


In [123]:
model_new = svm.SVC(kernel='linear', gamma='auto',C=20)
model_new.fit(X, Y)
predictions_poly = model_new.predict(x_test)

In [124]:
print(predictions_poly)

[8 1 4 ... 8 9 1]


In [126]:
print(classification_report(y_test,predictions_poly))

              precision    recall  f1-score   support

           0       0.42      0.17      0.24       355
           1       0.50      0.60      0.54       884
           2       0.00      0.00      0.00       203
           3       0.00      0.00      0.00        93
           4       0.79      0.92      0.85       756
           5       0.76      0.79      0.78       180
           6       0.00      0.00      0.00        88
           7       0.00      0.00      0.00        75
           8       0.46      0.55      0.50       986
           9       0.54      0.71      0.61       474

    accuracy                           0.56      4094
   macro avg       0.35      0.37      0.35      4094
weighted avg       0.49      0.56      0.52      4094



/Users/iknott/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [129]:
v = np.asarray(test_final)

In [130]:
v

array([[ 2, 35,  1, ...,  0,  3, 18],
       [ 0, 35,  1, ...,  0,  2,  8],
       [ 0, 28,  1, ...,  2,  2, 18],
       ...,
       [ 0, 27,  1, ...,  2,  2, 12],
       [ 0, 33,  1, ...,  0,  1, 10],
       [ 2, 26,  2, ...,  2,  2, 10]])

In [131]:
predictions_for_poly = model.predict(v)

In [132]:
print(predictions_for_poly)

[0 1 1 ... 8 0 8]


In [133]:
predictions_poly = model_new.predict(v)

In [134]:
print(predictions_poly)

[8 9 1 ... 1 8 1]


In [135]:
subm_csv.head(5)

EmpID BiasInfluentialFactor  FitmentPercent
0   5664         MaritalStatus           25.14
1  23568          DegreeBranch           91.44
2  21490         MartialStatus           76.92
3   8363         HighestDegree           77.92
4   6165                Gender           85.64

In [137]:
test_final['BiasInfluentialFactor'] = predictions_poly

In [138]:
test_final.head(4)

LanguageOfCommunication  Age  Gender  JobProfileIDApplyingFor  \
0                        2   35       1                        3   
1                        0   35       1                        3   
2                        0   28       1                        4   
3                        1   37       1                        4   

   HighestDegree  DegreeBranch  GraduatingInstitute  LatestDegreeCGPA  \
0              7             5                    1                 5   
1              0             5                    2                 9   
2              4             0                    1                 9   
3              6             1                    1                 8   

   YearsOfExperince  GraduationYear  CurrentCTC  ExpectedCTC  MartialStatus  \
0                 5               7          27           34              1   
1                12               0          29           33              0   
2                 2              10          18           25              0   
3                11               1           7           12              1   

   EmpScore  CurrentDesignation  CurrentCompanyType  DepartmentInCompany  \
0         4                   5                   0                    3   
1         4                   4                   0                    2   
2         3                   5                   2                    2   
3         5                   3                   0                    4   

   TotalLeavesTaken  BiasInfluentialFactor  
0                18                      8  
1                 8                      9  
2                18                      1  
3                17                      0

In [152]:
list_of

Never                 3336
DegreeBranch          2858
Gender                2605
YearsOfExperince      1561
CurrentCompanyType    1174
EmpScore               659
HighestDegree          582
Ethinicity             328
MartialStatus          280
LatestDegreeCGPA       262
Name: BiasInfluentialFactor, dtype: int64

In [161]:
final_df = pd.DataFrame()

In [162]:
final_df['EmpID'] = test_csv['EmpID']
final_df['BiasInfluentialFactor'] = test_final['BiasInfluentialFactor']

In [285]:
final_df['FitmentPercent'] = test_final['FitmentPercent']

In [163]:
final_df['BiasInfluentialFactor'] = final_df['BiasInfluentialFactor'].map({0:'NA',
                                                                           1:'DegreeBranch',
                                                                           2:'Gender',
                                                                           3:'YearsOfExperince',
                                                                           4:'CurrentCompanyType',
                                                                           5:'EmpScore',
                                                                           6:'HighestDegree',
                                                                           7:'Ethinicity',
                                                                           8:'MartialStatus',
                                                                           9:'LatestDegreeCGPA'
                                                                          })

In [286]:
final_df

EmpID BiasInfluentialFactor  FitmentPercent
0      5664         MartialStatus       69.956265
1     23568      LatestDegreeCGPA       71.282371
2     21490          DegreeBranch       78.483738
3      8363                    NA       66.007329
4      6165    CurrentCompanyType       89.520739
...     ...                   ...             ...
8740  14758    CurrentCompanyType       94.297140
8741  23544              EmpScore       80.130372
8742  16175          DegreeBranch       77.280930
8743  18458         MartialStatus       64.751069
8744  10036          DegreeBranch       73.548764

[8745 rows x 3 columns]

In [287]:
final_df.to_csv("data.csv", index = False)

In [288]:
subm_csv

EmpID BiasInfluentialFactor  FitmentPercent
0   5664         MaritalStatus           25.14
1  23568          DegreeBranch           91.44
2  21490         MartialStatus           76.92
3   8363         HighestDegree           77.92
4   6165                Gender           85.64
5  17679                   NaN           41.23
6   9715                   NaN           50.00